import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from './StoreProvider';
import ModalProvider from '../providers/ModalProvider/ModalProvider';

const inter = Inter({
  variable: '--font-inter',
  weight: ['400', '500', '600'],
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
    <body
      className={`${inter.variable} antialiased overflow-hidden`}
    >
    <StoreProvider>
      <ModalProvider>
        {children}
      </ModalProvider>
    </StoreProvider>
    </body>
    </html>
  );
}
